//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpositoresWeb03.ServiceReferenceCurso {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CursosDC", Namespace="http://schemas.datacontract.org/2004/07/WFC_Leon")]
    [System.SerializableAttribute()]
    public partial class CursosDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEspecialidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_cursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string comentariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estado_curField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_registroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_ult_modificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int horas_practicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int horas_teoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nivel_dificultadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuario_registroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuario_ult_modificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEspecialidad {
            get {
                return this.IdEspecialidadField;
            }
            set {
                if ((this.IdEspecialidadField.Equals(value) != true)) {
                    this.IdEspecialidadField = value;
                    this.RaisePropertyChanged("IdEspecialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_curso {
            get {
                return this.cod_cursoField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_cursoField, value) != true)) {
                    this.cod_cursoField = value;
                    this.RaisePropertyChanged("cod_curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comentarios {
            get {
                return this.comentariosField;
            }
            set {
                if ((object.ReferenceEquals(this.comentariosField, value) != true)) {
                    this.comentariosField = value;
                    this.RaisePropertyChanged("comentarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado_cur {
            get {
                return this.estado_curField;
            }
            set {
                if ((this.estado_curField.Equals(value) != true)) {
                    this.estado_curField = value;
                    this.RaisePropertyChanged("estado_cur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_registro {
            get {
                return this.fecha_registroField;
            }
            set {
                if ((this.fecha_registroField.Equals(value) != true)) {
                    this.fecha_registroField = value;
                    this.RaisePropertyChanged("fecha_registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_ult_modificacion {
            get {
                return this.fecha_ult_modificacionField;
            }
            set {
                if ((this.fecha_ult_modificacionField.Equals(value) != true)) {
                    this.fecha_ult_modificacionField = value;
                    this.RaisePropertyChanged("fecha_ult_modificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int horas_practica {
            get {
                return this.horas_practicaField;
            }
            set {
                if ((this.horas_practicaField.Equals(value) != true)) {
                    this.horas_practicaField = value;
                    this.RaisePropertyChanged("horas_practica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int horas_teoria {
            get {
                return this.horas_teoriaField;
            }
            set {
                if ((this.horas_teoriaField.Equals(value) != true)) {
                    this.horas_teoriaField = value;
                    this.RaisePropertyChanged("horas_teoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nivel_dificultad {
            get {
                return this.nivel_dificultadField;
            }
            set {
                if ((object.ReferenceEquals(this.nivel_dificultadField, value) != true)) {
                    this.nivel_dificultadField = value;
                    this.RaisePropertyChanged("nivel_dificultad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario_registro {
            get {
                return this.usuario_registroField;
            }
            set {
                if ((object.ReferenceEquals(this.usuario_registroField, value) != true)) {
                    this.usuario_registroField = value;
                    this.RaisePropertyChanged("usuario_registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario_ult_modificacion {
            get {
                return this.usuario_ult_modificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.usuario_ult_modificacionField, value) != true)) {
                    this.usuario_ult_modificacionField = value;
                    this.RaisePropertyChanged("usuario_ult_modificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EspecialidadDC", Namespace="http://schemas.datacontract.org/2004/07/WFC_Leon")]
    [System.SerializableAttribute()]
    public partial class EspecialidadDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescEspecialidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEspecialidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescEspecialidad {
            get {
                return this.DescEspecialidadField;
            }
            set {
                if ((object.ReferenceEquals(this.DescEspecialidadField, value) != true)) {
                    this.DescEspecialidadField = value;
                    this.RaisePropertyChanged("DescEspecialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEspecialidad {
            get {
                return this.IdEspecialidadField;
            }
            set {
                if ((this.IdEspecialidadField.Equals(value) != true)) {
                    this.IdEspecialidadField = value;
                    this.RaisePropertyChanged("IdEspecialidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCurso.IServicioCursos")]
    public interface IServicioCursos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/ListarCursos", ReplyAction="http://tempuri.org/IServicioCursos/ListarCursosResponse")]
        ExpositoresWeb03.ServiceReferenceCurso.CursosDC[] ListarCursos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/ListarCursos", ReplyAction="http://tempuri.org/IServicioCursos/ListarCursosResponse")]
        System.Threading.Tasks.Task<ExpositoresWeb03.ServiceReferenceCurso.CursosDC[]> ListarCursosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/ActualizarCursos", ReplyAction="http://tempuri.org/IServicioCursos/ActualizarCursosResponse")]
        bool ActualizarCursos(ExpositoresWeb03.ServiceReferenceCurso.CursosDC curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/ActualizarCursos", ReplyAction="http://tempuri.org/IServicioCursos/ActualizarCursosResponse")]
        System.Threading.Tasks.Task<bool> ActualizarCursosAsync(ExpositoresWeb03.ServiceReferenceCurso.CursosDC curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/EliminarCurso", ReplyAction="http://tempuri.org/IServicioCursos/EliminarCursoResponse")]
        bool EliminarCurso(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/EliminarCurso", ReplyAction="http://tempuri.org/IServicioCursos/EliminarCursoResponse")]
        System.Threading.Tasks.Task<bool> EliminarCursoAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/InsertarCurso", ReplyAction="http://tempuri.org/IServicioCursos/InsertarCursoResponse")]
        bool InsertarCurso(ExpositoresWeb03.ServiceReferenceCurso.CursosDC curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/InsertarCurso", ReplyAction="http://tempuri.org/IServicioCursos/InsertarCursoResponse")]
        System.Threading.Tasks.Task<bool> InsertarCursoAsync(ExpositoresWeb03.ServiceReferenceCurso.CursosDC curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/ConsultarCurso", ReplyAction="http://tempuri.org/IServicioCursos/ConsultarCursoResponse")]
        ExpositoresWeb03.ServiceReferenceCurso.CursosDC ConsultarCurso(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/ConsultarCurso", ReplyAction="http://tempuri.org/IServicioCursos/ConsultarCursoResponse")]
        System.Threading.Tasks.Task<ExpositoresWeb03.ServiceReferenceCurso.CursosDC> ConsultarCursoAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/ListarEspecialidad", ReplyAction="http://tempuri.org/IServicioCursos/ListarEspecialidadResponse")]
        ExpositoresWeb03.ServiceReferenceCurso.EspecialidadDC[] ListarEspecialidad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/ListarEspecialidad", ReplyAction="http://tempuri.org/IServicioCursos/ListarEspecialidadResponse")]
        System.Threading.Tasks.Task<ExpositoresWeb03.ServiceReferenceCurso.EspecialidadDC[]> ListarEspecialidadAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioCursosChannel : ExpositoresWeb03.ServiceReferenceCurso.IServicioCursos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCursosClient : System.ServiceModel.ClientBase<ExpositoresWeb03.ServiceReferenceCurso.IServicioCursos>, ExpositoresWeb03.ServiceReferenceCurso.IServicioCursos {
        
        public ServicioCursosClient() {
        }
        
        public ServicioCursosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCursosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCursosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCursosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ExpositoresWeb03.ServiceReferenceCurso.CursosDC[] ListarCursos() {
            return base.Channel.ListarCursos();
        }
        
        public System.Threading.Tasks.Task<ExpositoresWeb03.ServiceReferenceCurso.CursosDC[]> ListarCursosAsync() {
            return base.Channel.ListarCursosAsync();
        }
        
        public bool ActualizarCursos(ExpositoresWeb03.ServiceReferenceCurso.CursosDC curso) {
            return base.Channel.ActualizarCursos(curso);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarCursosAsync(ExpositoresWeb03.ServiceReferenceCurso.CursosDC curso) {
            return base.Channel.ActualizarCursosAsync(curso);
        }
        
        public bool EliminarCurso(string strCodigo) {
            return base.Channel.EliminarCurso(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarCursoAsync(string strCodigo) {
            return base.Channel.EliminarCursoAsync(strCodigo);
        }
        
        public bool InsertarCurso(ExpositoresWeb03.ServiceReferenceCurso.CursosDC curso) {
            return base.Channel.InsertarCurso(curso);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarCursoAsync(ExpositoresWeb03.ServiceReferenceCurso.CursosDC curso) {
            return base.Channel.InsertarCursoAsync(curso);
        }
        
        public ExpositoresWeb03.ServiceReferenceCurso.CursosDC ConsultarCurso(string id) {
            return base.Channel.ConsultarCurso(id);
        }
        
        public System.Threading.Tasks.Task<ExpositoresWeb03.ServiceReferenceCurso.CursosDC> ConsultarCursoAsync(string id) {
            return base.Channel.ConsultarCursoAsync(id);
        }
        
        public ExpositoresWeb03.ServiceReferenceCurso.EspecialidadDC[] ListarEspecialidad() {
            return base.Channel.ListarEspecialidad();
        }
        
        public System.Threading.Tasks.Task<ExpositoresWeb03.ServiceReferenceCurso.EspecialidadDC[]> ListarEspecialidadAsync() {
            return base.Channel.ListarEspecialidadAsync();
        }
    }
}
