//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Consultas.ServiceReferenceAsociado {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AsociadosDC", Namespace="http://schemas.datacontract.org/2004/07/WFC_Leon")]
    [System.SerializableAttribute()]
    public partial class AsociadosDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Id_EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_UbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ape_maternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ape_paternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_asociadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estado_asoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fech_ult_capacitacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_ingresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_registroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_ult_modificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] fotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tlf_celularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tlf_domicilioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuario_registroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuario_ult_modificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id_Empresa {
            get {
                return this.Id_EmpresaField;
            }
            set {
                if ((this.Id_EmpresaField.Equals(value) != true)) {
                    this.Id_EmpresaField = value;
                    this.RaisePropertyChanged("Id_Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ubigeo {
            get {
                return this.Id_UbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_UbigeoField, value) != true)) {
                    this.Id_UbigeoField = value;
                    this.RaisePropertyChanged("Id_Ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ape_materno {
            get {
                return this.ape_maternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ape_maternoField, value) != true)) {
                    this.ape_maternoField = value;
                    this.RaisePropertyChanged("ape_materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ape_paterno {
            get {
                return this.ape_paternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ape_paternoField, value) != true)) {
                    this.ape_paternoField = value;
                    this.RaisePropertyChanged("ape_paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_asociado {
            get {
                return this.cod_asociadoField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_asociadoField, value) != true)) {
                    this.cod_asociadoField = value;
                    this.RaisePropertyChanged("cod_asociado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                if ((object.ReferenceEquals(this.dniField, value) != true)) {
                    this.dniField = value;
                    this.RaisePropertyChanged("dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado_aso {
            get {
                return this.estado_asoField;
            }
            set {
                if ((this.estado_asoField.Equals(value) != true)) {
                    this.estado_asoField = value;
                    this.RaisePropertyChanged("estado_aso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fech_ult_capacitacion {
            get {
                return this.fech_ult_capacitacionField;
            }
            set {
                if ((this.fech_ult_capacitacionField.Equals(value) != true)) {
                    this.fech_ult_capacitacionField = value;
                    this.RaisePropertyChanged("fech_ult_capacitacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_ingreso {
            get {
                return this.fecha_ingresoField;
            }
            set {
                if ((this.fecha_ingresoField.Equals(value) != true)) {
                    this.fecha_ingresoField = value;
                    this.RaisePropertyChanged("fecha_ingreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_registro {
            get {
                return this.fecha_registroField;
            }
            set {
                if ((this.fecha_registroField.Equals(value) != true)) {
                    this.fecha_registroField = value;
                    this.RaisePropertyChanged("fecha_registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_ult_modificacion {
            get {
                return this.fecha_ult_modificacionField;
            }
            set {
                if ((this.fecha_ult_modificacionField.Equals(value) != true)) {
                    this.fecha_ult_modificacionField = value;
                    this.RaisePropertyChanged("fecha_ult_modificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoField, value) != true)) {
                    this.fotoField = value;
                    this.RaisePropertyChanged("foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.nombresField, value) != true)) {
                    this.nombresField = value;
                    this.RaisePropertyChanged("nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tlf_celular {
            get {
                return this.tlf_celularField;
            }
            set {
                if ((object.ReferenceEquals(this.tlf_celularField, value) != true)) {
                    this.tlf_celularField = value;
                    this.RaisePropertyChanged("tlf_celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tlf_domicilio {
            get {
                return this.tlf_domicilioField;
            }
            set {
                if ((object.ReferenceEquals(this.tlf_domicilioField, value) != true)) {
                    this.tlf_domicilioField = value;
                    this.RaisePropertyChanged("tlf_domicilio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario_registro {
            get {
                return this.usuario_registroField;
            }
            set {
                if ((object.ReferenceEquals(this.usuario_registroField, value) != true)) {
                    this.usuario_registroField = value;
                    this.RaisePropertyChanged("usuario_registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario_ult_modificacion {
            get {
                return this.usuario_ult_modificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.usuario_ult_modificacionField, value) != true)) {
                    this.usuario_ult_modificacionField = value;
                    this.RaisePropertyChanged("usuario_ult_modificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpresasDC", Namespace="http://schemas.datacontract.org/2004/07/WFC_Leon")]
    [System.SerializableAttribute()]
    public partial class EmpresasDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_UbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Razon_SocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Telefono1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Telefono2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlPagWebField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estado_empField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_registroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_ult_modificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuario_ult_modificacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Empresa {
            get {
                return this.Id_EmpresaField;
            }
            set {
                if ((this.Id_EmpresaField.Equals(value) != true)) {
                    this.Id_EmpresaField = value;
                    this.RaisePropertyChanged("Id_Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ubigeo {
            get {
                return this.Id_UbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_UbigeoField, value) != true)) {
                    this.Id_UbigeoField = value;
                    this.RaisePropertyChanged("Id_Ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Razon_Social {
            get {
                return this.Razon_SocialField;
            }
            set {
                if ((object.ReferenceEquals(this.Razon_SocialField, value) != true)) {
                    this.Razon_SocialField = value;
                    this.RaisePropertyChanged("Razon_Social");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono1 {
            get {
                return this.Telefono1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Telefono1Field, value) != true)) {
                    this.Telefono1Field = value;
                    this.RaisePropertyChanged("Telefono1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono2 {
            get {
                return this.Telefono2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Telefono2Field, value) != true)) {
                    this.Telefono2Field = value;
                    this.RaisePropertyChanged("Telefono2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlPagWeb {
            get {
                return this.UrlPagWebField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlPagWebField, value) != true)) {
                    this.UrlPagWebField = value;
                    this.RaisePropertyChanged("UrlPagWeb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado_emp {
            get {
                return this.estado_empField;
            }
            set {
                if ((this.estado_empField.Equals(value) != true)) {
                    this.estado_empField = value;
                    this.RaisePropertyChanged("estado_emp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_registro {
            get {
                return this.fecha_registroField;
            }
            set {
                if ((this.fecha_registroField.Equals(value) != true)) {
                    this.fecha_registroField = value;
                    this.RaisePropertyChanged("fecha_registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_ult_modificacion {
            get {
                return this.fecha_ult_modificacionField;
            }
            set {
                if ((this.fecha_ult_modificacionField.Equals(value) != true)) {
                    this.fecha_ult_modificacionField = value;
                    this.RaisePropertyChanged("fecha_ult_modificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario_ult_modificacion {
            get {
                return this.usuario_ult_modificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.usuario_ult_modificacionField, value) != true)) {
                    this.usuario_ult_modificacionField = value;
                    this.RaisePropertyChanged("usuario_ult_modificacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAsociado.IServicioAsociados")]
    public interface IServicioAsociados {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAsociados/ListarAsociados", ReplyAction="http://tempuri.org/IServicioAsociados/ListarAsociadosResponse")]
        MVC_Consultas.ServiceReferenceAsociado.AsociadosDC[] ListarAsociados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAsociados/ListarAsociados", ReplyAction="http://tempuri.org/IServicioAsociados/ListarAsociadosResponse")]
        System.Threading.Tasks.Task<MVC_Consultas.ServiceReferenceAsociado.AsociadosDC[]> ListarAsociadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAsociados/ActualizarAsociados", ReplyAction="http://tempuri.org/IServicioAsociados/ActualizarAsociadosResponse")]
        bool ActualizarAsociados(MVC_Consultas.ServiceReferenceAsociado.AsociadosDC asociado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAsociados/ActualizarAsociados", ReplyAction="http://tempuri.org/IServicioAsociados/ActualizarAsociadosResponse")]
        System.Threading.Tasks.Task<bool> ActualizarAsociadosAsync(MVC_Consultas.ServiceReferenceAsociado.AsociadosDC asociado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAsociados/EliminarAsociados", ReplyAction="http://tempuri.org/IServicioAsociados/EliminarAsociadosResponse")]
        bool EliminarAsociados(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAsociados/EliminarAsociados", ReplyAction="http://tempuri.org/IServicioAsociados/EliminarAsociadosResponse")]
        System.Threading.Tasks.Task<bool> EliminarAsociadosAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAsociados/InsertarAsociados", ReplyAction="http://tempuri.org/IServicioAsociados/InsertarAsociadosResponse")]
        bool InsertarAsociados(MVC_Consultas.ServiceReferenceAsociado.AsociadosDC asociado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAsociados/InsertarAsociados", ReplyAction="http://tempuri.org/IServicioAsociados/InsertarAsociadosResponse")]
        System.Threading.Tasks.Task<bool> InsertarAsociadosAsync(MVC_Consultas.ServiceReferenceAsociado.AsociadosDC asociado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAsociados/ConsultarAsociado", ReplyAction="http://tempuri.org/IServicioAsociados/ConsultarAsociadoResponse")]
        MVC_Consultas.ServiceReferenceAsociado.AsociadosDC ConsultarAsociado(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAsociados/ConsultarAsociado", ReplyAction="http://tempuri.org/IServicioAsociados/ConsultarAsociadoResponse")]
        System.Threading.Tasks.Task<MVC_Consultas.ServiceReferenceAsociado.AsociadosDC> ConsultarAsociadoAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAsociados/ListarEmpresas", ReplyAction="http://tempuri.org/IServicioAsociados/ListarEmpresasResponse")]
        MVC_Consultas.ServiceReferenceAsociado.EmpresasDC[] ListarEmpresas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAsociados/ListarEmpresas", ReplyAction="http://tempuri.org/IServicioAsociados/ListarEmpresasResponse")]
        System.Threading.Tasks.Task<MVC_Consultas.ServiceReferenceAsociado.EmpresasDC[]> ListarEmpresasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioAsociadosChannel : MVC_Consultas.ServiceReferenceAsociado.IServicioAsociados, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioAsociadosClient : System.ServiceModel.ClientBase<MVC_Consultas.ServiceReferenceAsociado.IServicioAsociados>, MVC_Consultas.ServiceReferenceAsociado.IServicioAsociados {
        
        public ServicioAsociadosClient() {
        }
        
        public ServicioAsociadosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioAsociadosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAsociadosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAsociadosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVC_Consultas.ServiceReferenceAsociado.AsociadosDC[] ListarAsociados() {
            return base.Channel.ListarAsociados();
        }
        
        public System.Threading.Tasks.Task<MVC_Consultas.ServiceReferenceAsociado.AsociadosDC[]> ListarAsociadosAsync() {
            return base.Channel.ListarAsociadosAsync();
        }
        
        public bool ActualizarAsociados(MVC_Consultas.ServiceReferenceAsociado.AsociadosDC asociado) {
            return base.Channel.ActualizarAsociados(asociado);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarAsociadosAsync(MVC_Consultas.ServiceReferenceAsociado.AsociadosDC asociado) {
            return base.Channel.ActualizarAsociadosAsync(asociado);
        }
        
        public bool EliminarAsociados(string strCodigo) {
            return base.Channel.EliminarAsociados(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarAsociadosAsync(string strCodigo) {
            return base.Channel.EliminarAsociadosAsync(strCodigo);
        }
        
        public bool InsertarAsociados(MVC_Consultas.ServiceReferenceAsociado.AsociadosDC asociado) {
            return base.Channel.InsertarAsociados(asociado);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarAsociadosAsync(MVC_Consultas.ServiceReferenceAsociado.AsociadosDC asociado) {
            return base.Channel.InsertarAsociadosAsync(asociado);
        }
        
        public MVC_Consultas.ServiceReferenceAsociado.AsociadosDC ConsultarAsociado(string id) {
            return base.Channel.ConsultarAsociado(id);
        }
        
        public System.Threading.Tasks.Task<MVC_Consultas.ServiceReferenceAsociado.AsociadosDC> ConsultarAsociadoAsync(string id) {
            return base.Channel.ConsultarAsociadoAsync(id);
        }
        
        public MVC_Consultas.ServiceReferenceAsociado.EmpresasDC[] ListarEmpresas() {
            return base.Channel.ListarEmpresas();
        }
        
        public System.Threading.Tasks.Task<MVC_Consultas.ServiceReferenceAsociado.EmpresasDC[]> ListarEmpresasAsync() {
            return base.Channel.ListarEmpresasAsync();
        }
    }
}
