//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Consultas.ServiceReferenceEventos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventosDc", Namespace="http://schemas.datacontract.org/2004/07/WFC_Leon")]
    [System.SerializableAttribute()]
    public partial class EventosDc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AsociadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpositorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LugarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TurnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_asociadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estado_eveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_finField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_inicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_eventoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Asociado {
            get {
                return this.AsociadoField;
            }
            set {
                if ((object.ReferenceEquals(this.AsociadoField, value) != true)) {
                    this.AsociadoField = value;
                    this.RaisePropertyChanged("Asociado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Evento {
            get {
                return this.EventoField;
            }
            set {
                if ((object.ReferenceEquals(this.EventoField, value) != true)) {
                    this.EventoField = value;
                    this.RaisePropertyChanged("Evento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Expositor {
            get {
                return this.ExpositorField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpositorField, value) != true)) {
                    this.ExpositorField = value;
                    this.RaisePropertyChanged("Expositor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lugar {
            get {
                return this.LugarField;
            }
            set {
                if ((object.ReferenceEquals(this.LugarField, value) != true)) {
                    this.LugarField = value;
                    this.RaisePropertyChanged("Lugar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Turno {
            get {
                return this.TurnoField;
            }
            set {
                if ((object.ReferenceEquals(this.TurnoField, value) != true)) {
                    this.TurnoField = value;
                    this.RaisePropertyChanged("Turno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cod_asociado {
            get {
                return this.cod_asociadoField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_asociadoField, value) != true)) {
                    this.cod_asociadoField = value;
                    this.RaisePropertyChanged("cod_asociado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado_eve {
            get {
                return this.estado_eveField;
            }
            set {
                if ((object.ReferenceEquals(this.estado_eveField, value) != true)) {
                    this.estado_eveField = value;
                    this.RaisePropertyChanged("estado_eve");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_fin {
            get {
                return this.fecha_finField;
            }
            set {
                if ((this.fecha_finField.Equals(value) != true)) {
                    this.fecha_finField = value;
                    this.RaisePropertyChanged("fecha_fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_inicio {
            get {
                return this.fecha_inicioField;
            }
            set {
                if ((this.fecha_inicioField.Equals(value) != true)) {
                    this.fecha_inicioField = value;
                    this.RaisePropertyChanged("fecha_inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_evento {
            get {
                return this.id_eventoField;
            }
            set {
                if ((this.id_eventoField.Equals(value) != true)) {
                    this.id_eventoField = value;
                    this.RaisePropertyChanged("id_evento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceEventos.IServicioConsultaInscripcionEvento")]
    public interface IServicioConsultaInscripcionEvento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultaInscripcionEvento/consultarEventos", ReplyAction="http://tempuri.org/IServicioConsultaInscripcionEvento/consultarEventosResponse")]
        MVC_Consultas.ServiceReferenceEventos.EventosDc[] consultarEventos(string lugar, string turno, string expositor, int empresa, string codAsociado, string apeAsociado, System.DateTime fechaInicio, System.DateTime fechaFin, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultaInscripcionEvento/consultarEventos", ReplyAction="http://tempuri.org/IServicioConsultaInscripcionEvento/consultarEventosResponse")]
        System.Threading.Tasks.Task<MVC_Consultas.ServiceReferenceEventos.EventosDc[]> consultarEventosAsync(string lugar, string turno, string expositor, int empresa, string codAsociado, string apeAsociado, System.DateTime fechaInicio, System.DateTime fechaFin, int estado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioConsultaInscripcionEventoChannel : MVC_Consultas.ServiceReferenceEventos.IServicioConsultaInscripcionEvento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioConsultaInscripcionEventoClient : System.ServiceModel.ClientBase<MVC_Consultas.ServiceReferenceEventos.IServicioConsultaInscripcionEvento>, MVC_Consultas.ServiceReferenceEventos.IServicioConsultaInscripcionEvento {
        
        public ServicioConsultaInscripcionEventoClient() {
        }
        
        public ServicioConsultaInscripcionEventoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioConsultaInscripcionEventoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioConsultaInscripcionEventoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioConsultaInscripcionEventoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVC_Consultas.ServiceReferenceEventos.EventosDc[] consultarEventos(string lugar, string turno, string expositor, int empresa, string codAsociado, string apeAsociado, System.DateTime fechaInicio, System.DateTime fechaFin, int estado) {
            return base.Channel.consultarEventos(lugar, turno, expositor, empresa, codAsociado, apeAsociado, fechaInicio, fechaFin, estado);
        }
        
        public System.Threading.Tasks.Task<MVC_Consultas.ServiceReferenceEventos.EventosDc[]> consultarEventosAsync(string lugar, string turno, string expositor, int empresa, string codAsociado, string apeAsociado, System.DateTime fechaInicio, System.DateTime fechaFin, int estado) {
            return base.Channel.consultarEventosAsync(lugar, turno, expositor, empresa, codAsociado, apeAsociado, fechaInicio, fechaFin, estado);
        }
    }
}
