//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFC_Leon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LeonComputingEntities9 : DbContext
    {
        public LeonComputingEntities9()
            : base("name=LeonComputingEntities9")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Asociado> Tb_Asociado { get; set; }
        public virtual DbSet<Tb_Curso> Tb_Curso { get; set; }
        public virtual DbSet<Tb_Empresa> Tb_Empresa { get; set; }
        public virtual DbSet<Tb_Especialidad> Tb_Especialidad { get; set; }
        public virtual DbSet<Tb_Evento> Tb_Evento { get; set; }
        public virtual DbSet<Tb_Expositor> Tb_Expositor { get; set; }
        public virtual DbSet<Tb_Expositor_Empresa> Tb_Expositor_Empresa { get; set; }
        public virtual DbSet<Tb_Ubigeo> Tb_Ubigeo { get; set; }
        public virtual DbSet<Tb_Usuario> Tb_Usuario { get; set; }
    
        public virtual int usp_ActualizarAsistenciaSocio(string vcod_asociado, Nullable<int> vid_evento)
        {
            var vcod_asociadoParameter = vcod_asociado != null ?
                new ObjectParameter("vcod_asociado", vcod_asociado) :
                new ObjectParameter("vcod_asociado", typeof(string));
    
            var vid_eventoParameter = vid_evento.HasValue ?
                new ObjectParameter("vid_evento", vid_evento) :
                new ObjectParameter("vid_evento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarAsistenciaSocio", vcod_asociadoParameter, vid_eventoParameter);
        }
    
        public virtual int usp_ActualizarAsociado(string vcod_asociado, string vape_paterno, string vape_materno, string vnombres, string vdireccion, string vdni, byte[] vfoto, string vtlf_domicilio, string vtlf_celular, string vcorreo, Nullable<int> vId_Empresa, string vId_Ubigeo, string vusuario_ult_modificacion, Nullable<int> vestado_aso)
        {
            var vcod_asociadoParameter = vcod_asociado != null ?
                new ObjectParameter("vcod_asociado", vcod_asociado) :
                new ObjectParameter("vcod_asociado", typeof(string));
    
            var vape_paternoParameter = vape_paterno != null ?
                new ObjectParameter("vape_paterno", vape_paterno) :
                new ObjectParameter("vape_paterno", typeof(string));
    
            var vape_maternoParameter = vape_materno != null ?
                new ObjectParameter("vape_materno", vape_materno) :
                new ObjectParameter("vape_materno", typeof(string));
    
            var vnombresParameter = vnombres != null ?
                new ObjectParameter("vnombres", vnombres) :
                new ObjectParameter("vnombres", typeof(string));
    
            var vdireccionParameter = vdireccion != null ?
                new ObjectParameter("vdireccion", vdireccion) :
                new ObjectParameter("vdireccion", typeof(string));
    
            var vdniParameter = vdni != null ?
                new ObjectParameter("vdni", vdni) :
                new ObjectParameter("vdni", typeof(string));
    
            var vfotoParameter = vfoto != null ?
                new ObjectParameter("vfoto", vfoto) :
                new ObjectParameter("vfoto", typeof(byte[]));
    
            var vtlf_domicilioParameter = vtlf_domicilio != null ?
                new ObjectParameter("vtlf_domicilio", vtlf_domicilio) :
                new ObjectParameter("vtlf_domicilio", typeof(string));
    
            var vtlf_celularParameter = vtlf_celular != null ?
                new ObjectParameter("vtlf_celular", vtlf_celular) :
                new ObjectParameter("vtlf_celular", typeof(string));
    
            var vcorreoParameter = vcorreo != null ?
                new ObjectParameter("vcorreo", vcorreo) :
                new ObjectParameter("vcorreo", typeof(string));
    
            var vId_EmpresaParameter = vId_Empresa.HasValue ?
                new ObjectParameter("vId_Empresa", vId_Empresa) :
                new ObjectParameter("vId_Empresa", typeof(int));
    
            var vId_UbigeoParameter = vId_Ubigeo != null ?
                new ObjectParameter("vId_Ubigeo", vId_Ubigeo) :
                new ObjectParameter("vId_Ubigeo", typeof(string));
    
            var vusuario_ult_modificacionParameter = vusuario_ult_modificacion != null ?
                new ObjectParameter("vusuario_ult_modificacion", vusuario_ult_modificacion) :
                new ObjectParameter("vusuario_ult_modificacion", typeof(string));
    
            var vestado_asoParameter = vestado_aso.HasValue ?
                new ObjectParameter("vestado_aso", vestado_aso) :
                new ObjectParameter("vestado_aso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarAsociado", vcod_asociadoParameter, vape_paternoParameter, vape_maternoParameter, vnombresParameter, vdireccionParameter, vdniParameter, vfotoParameter, vtlf_domicilioParameter, vtlf_celularParameter, vcorreoParameter, vId_EmpresaParameter, vId_UbigeoParameter, vusuario_ult_modificacionParameter, vestado_asoParameter);
        }
    
        public virtual int usp_ActualizarCurso(string vcod_curso, string vdescripcion, Nullable<int> vhoras_teoria, Nullable<int> vhoras_practica, string vnivel_dificultad, string vcomentarios, Nullable<int> vIdEspecialidad, string vusuario_ult_modificacion, Nullable<int> vestado_cur)
        {
            var vcod_cursoParameter = vcod_curso != null ?
                new ObjectParameter("vcod_curso", vcod_curso) :
                new ObjectParameter("vcod_curso", typeof(string));
    
            var vdescripcionParameter = vdescripcion != null ?
                new ObjectParameter("vdescripcion", vdescripcion) :
                new ObjectParameter("vdescripcion", typeof(string));
    
            var vhoras_teoriaParameter = vhoras_teoria.HasValue ?
                new ObjectParameter("vhoras_teoria", vhoras_teoria) :
                new ObjectParameter("vhoras_teoria", typeof(int));
    
            var vhoras_practicaParameter = vhoras_practica.HasValue ?
                new ObjectParameter("vhoras_practica", vhoras_practica) :
                new ObjectParameter("vhoras_practica", typeof(int));
    
            var vnivel_dificultadParameter = vnivel_dificultad != null ?
                new ObjectParameter("vnivel_dificultad", vnivel_dificultad) :
                new ObjectParameter("vnivel_dificultad", typeof(string));
    
            var vcomentariosParameter = vcomentarios != null ?
                new ObjectParameter("vcomentarios", vcomentarios) :
                new ObjectParameter("vcomentarios", typeof(string));
    
            var vIdEspecialidadParameter = vIdEspecialidad.HasValue ?
                new ObjectParameter("vIdEspecialidad", vIdEspecialidad) :
                new ObjectParameter("vIdEspecialidad", typeof(int));
    
            var vusuario_ult_modificacionParameter = vusuario_ult_modificacion != null ?
                new ObjectParameter("vusuario_ult_modificacion", vusuario_ult_modificacion) :
                new ObjectParameter("vusuario_ult_modificacion", typeof(string));
    
            var vestado_curParameter = vestado_cur.HasValue ?
                new ObjectParameter("vestado_cur", vestado_cur) :
                new ObjectParameter("vestado_cur", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarCurso", vcod_cursoParameter, vdescripcionParameter, vhoras_teoriaParameter, vhoras_practicaParameter, vnivel_dificultadParameter, vcomentariosParameter, vIdEspecialidadParameter, vusuario_ult_modificacionParameter, vestado_curParameter);
        }
    
        public virtual int usp_ActualizarEmpresa(Nullable<int> vId_Empresa, string vRazon_Social, string vDireccion, string vTelefono1, string vTelefono2, string vUrlPagWeb, string vId_Ubigeo, Nullable<System.DateTime> vfecha_registro, string vusuario_ult_modificacion, Nullable<System.DateTime> vfecha_ult_modificacion, Nullable<int> vestado_emp)
        {
            var vId_EmpresaParameter = vId_Empresa.HasValue ?
                new ObjectParameter("vId_Empresa", vId_Empresa) :
                new ObjectParameter("vId_Empresa", typeof(int));
    
            var vRazon_SocialParameter = vRazon_Social != null ?
                new ObjectParameter("vRazon_Social", vRazon_Social) :
                new ObjectParameter("vRazon_Social", typeof(string));
    
            var vDireccionParameter = vDireccion != null ?
                new ObjectParameter("vDireccion", vDireccion) :
                new ObjectParameter("vDireccion", typeof(string));
    
            var vTelefono1Parameter = vTelefono1 != null ?
                new ObjectParameter("vTelefono1", vTelefono1) :
                new ObjectParameter("vTelefono1", typeof(string));
    
            var vTelefono2Parameter = vTelefono2 != null ?
                new ObjectParameter("vTelefono2", vTelefono2) :
                new ObjectParameter("vTelefono2", typeof(string));
    
            var vUrlPagWebParameter = vUrlPagWeb != null ?
                new ObjectParameter("vUrlPagWeb", vUrlPagWeb) :
                new ObjectParameter("vUrlPagWeb", typeof(string));
    
            var vId_UbigeoParameter = vId_Ubigeo != null ?
                new ObjectParameter("vId_Ubigeo", vId_Ubigeo) :
                new ObjectParameter("vId_Ubigeo", typeof(string));
    
            var vfecha_registroParameter = vfecha_registro.HasValue ?
                new ObjectParameter("vfecha_registro", vfecha_registro) :
                new ObjectParameter("vfecha_registro", typeof(System.DateTime));
    
            var vusuario_ult_modificacionParameter = vusuario_ult_modificacion != null ?
                new ObjectParameter("vusuario_ult_modificacion", vusuario_ult_modificacion) :
                new ObjectParameter("vusuario_ult_modificacion", typeof(string));
    
            var vfecha_ult_modificacionParameter = vfecha_ult_modificacion.HasValue ?
                new ObjectParameter("vfecha_ult_modificacion", vfecha_ult_modificacion) :
                new ObjectParameter("vfecha_ult_modificacion", typeof(System.DateTime));
    
            var vestado_empParameter = vestado_emp.HasValue ?
                new ObjectParameter("vestado_emp", vestado_emp) :
                new ObjectParameter("vestado_emp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarEmpresa", vId_EmpresaParameter, vRazon_SocialParameter, vDireccionParameter, vTelefono1Parameter, vTelefono2Parameter, vUrlPagWebParameter, vId_UbigeoParameter, vfecha_registroParameter, vusuario_ult_modificacionParameter, vfecha_ult_modificacionParameter, vestado_empParameter);
        }
    
        public virtual int usp_ActualizarEspecialidad(Nullable<int> vIdEspecialidad, string vDescEspecialidad)
        {
            var vIdEspecialidadParameter = vIdEspecialidad.HasValue ?
                new ObjectParameter("vIdEspecialidad", vIdEspecialidad) :
                new ObjectParameter("vIdEspecialidad", typeof(int));
    
            var vDescEspecialidadParameter = vDescEspecialidad != null ?
                new ObjectParameter("vDescEspecialidad", vDescEspecialidad) :
                new ObjectParameter("vDescEspecialidad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarEspecialidad", vIdEspecialidadParameter, vDescEspecialidadParameter);
        }
    
        public virtual int usp_ActualizarEspecialidadExpositor(Nullable<int> vCod_EspecialidadCurso, Nullable<int> vIdEspecialidad, string vId_Expositor)
        {
            var vCod_EspecialidadCursoParameter = vCod_EspecialidadCurso.HasValue ?
                new ObjectParameter("vCod_EspecialidadCurso", vCod_EspecialidadCurso) :
                new ObjectParameter("vCod_EspecialidadCurso", typeof(int));
    
            var vIdEspecialidadParameter = vIdEspecialidad.HasValue ?
                new ObjectParameter("vIdEspecialidad", vIdEspecialidad) :
                new ObjectParameter("vIdEspecialidad", typeof(int));
    
            var vId_ExpositorParameter = vId_Expositor != null ?
                new ObjectParameter("vId_Expositor", vId_Expositor) :
                new ObjectParameter("vId_Expositor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarEspecialidadExpositor", vCod_EspecialidadCursoParameter, vIdEspecialidadParameter, vId_ExpositorParameter);
        }
    
        public virtual int usp_ActualizarEvento(Nullable<int> vid_evento, Nullable<int> vId_Empresa, Nullable<int> vid_frecuencia, Nullable<int> vid_turno, Nullable<decimal> vpresupuesto_requerido, string vdireccion_evento, Nullable<int> vcupos_programados, Nullable<System.DateTime> vfecha_inicio, Nullable<System.DateTime> vfecha_fin, string vId_Expositor, string vId_Ubigeo, string vcod_curso, string vusuario_ult_modificacion, Nullable<int> vestado_eve)
        {
            var vid_eventoParameter = vid_evento.HasValue ?
                new ObjectParameter("vid_evento", vid_evento) :
                new ObjectParameter("vid_evento", typeof(int));
    
            var vId_EmpresaParameter = vId_Empresa.HasValue ?
                new ObjectParameter("vId_Empresa", vId_Empresa) :
                new ObjectParameter("vId_Empresa", typeof(int));
    
            var vid_frecuenciaParameter = vid_frecuencia.HasValue ?
                new ObjectParameter("vid_frecuencia", vid_frecuencia) :
                new ObjectParameter("vid_frecuencia", typeof(int));
    
            var vid_turnoParameter = vid_turno.HasValue ?
                new ObjectParameter("vid_turno", vid_turno) :
                new ObjectParameter("vid_turno", typeof(int));
    
            var vpresupuesto_requeridoParameter = vpresupuesto_requerido.HasValue ?
                new ObjectParameter("vpresupuesto_requerido", vpresupuesto_requerido) :
                new ObjectParameter("vpresupuesto_requerido", typeof(decimal));
    
            var vdireccion_eventoParameter = vdireccion_evento != null ?
                new ObjectParameter("vdireccion_evento", vdireccion_evento) :
                new ObjectParameter("vdireccion_evento", typeof(string));
    
            var vcupos_programadosParameter = vcupos_programados.HasValue ?
                new ObjectParameter("vcupos_programados", vcupos_programados) :
                new ObjectParameter("vcupos_programados", typeof(int));
    
            var vfecha_inicioParameter = vfecha_inicio.HasValue ?
                new ObjectParameter("vfecha_inicio", vfecha_inicio) :
                new ObjectParameter("vfecha_inicio", typeof(System.DateTime));
    
            var vfecha_finParameter = vfecha_fin.HasValue ?
                new ObjectParameter("vfecha_fin", vfecha_fin) :
                new ObjectParameter("vfecha_fin", typeof(System.DateTime));
    
            var vId_ExpositorParameter = vId_Expositor != null ?
                new ObjectParameter("vId_Expositor", vId_Expositor) :
                new ObjectParameter("vId_Expositor", typeof(string));
    
            var vId_UbigeoParameter = vId_Ubigeo != null ?
                new ObjectParameter("vId_Ubigeo", vId_Ubigeo) :
                new ObjectParameter("vId_Ubigeo", typeof(string));
    
            var vcod_cursoParameter = vcod_curso != null ?
                new ObjectParameter("vcod_curso", vcod_curso) :
                new ObjectParameter("vcod_curso", typeof(string));
    
            var vusuario_ult_modificacionParameter = vusuario_ult_modificacion != null ?
                new ObjectParameter("vusuario_ult_modificacion", vusuario_ult_modificacion) :
                new ObjectParameter("vusuario_ult_modificacion", typeof(string));
    
            var vestado_eveParameter = vestado_eve.HasValue ?
                new ObjectParameter("vestado_eve", vestado_eve) :
                new ObjectParameter("vestado_eve", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarEvento", vid_eventoParameter, vId_EmpresaParameter, vid_frecuenciaParameter, vid_turnoParameter, vpresupuesto_requeridoParameter, vdireccion_eventoParameter, vcupos_programadosParameter, vfecha_inicioParameter, vfecha_finParameter, vId_ExpositorParameter, vId_UbigeoParameter, vcod_cursoParameter, vusuario_ult_modificacionParameter, vestado_eveParameter);
        }
    
        public virtual int usp_ActualizarExpositor(string vId_Expositor, string vApellido_materno, string vApellido_paterno, string vNombre, string vDirección, string vTelefono, string vE_mail, string vDNI, byte[] vFoto_Expositor, string vComentario, string vId_Ubigeo, Nullable<System.DateTime> vfecha_registro, string vusuario_ult_modificacion, Nullable<System.DateTime> vfecha_ult_modificacion, Nullable<int> vestado_exp)
        {
            var vId_ExpositorParameter = vId_Expositor != null ?
                new ObjectParameter("vId_Expositor", vId_Expositor) :
                new ObjectParameter("vId_Expositor", typeof(string));
    
            var vApellido_maternoParameter = vApellido_materno != null ?
                new ObjectParameter("vApellido_materno", vApellido_materno) :
                new ObjectParameter("vApellido_materno", typeof(string));
    
            var vApellido_paternoParameter = vApellido_paterno != null ?
                new ObjectParameter("vApellido_paterno", vApellido_paterno) :
                new ObjectParameter("vApellido_paterno", typeof(string));
    
            var vNombreParameter = vNombre != null ?
                new ObjectParameter("vNombre", vNombre) :
                new ObjectParameter("vNombre", typeof(string));
    
            var vDirecciónParameter = vDirección != null ?
                new ObjectParameter("vDirección", vDirección) :
                new ObjectParameter("vDirección", typeof(string));
    
            var vTelefonoParameter = vTelefono != null ?
                new ObjectParameter("vTelefono", vTelefono) :
                new ObjectParameter("vTelefono", typeof(string));
    
            var vE_mailParameter = vE_mail != null ?
                new ObjectParameter("vE_mail", vE_mail) :
                new ObjectParameter("vE_mail", typeof(string));
    
            var vDNIParameter = vDNI != null ?
                new ObjectParameter("vDNI", vDNI) :
                new ObjectParameter("vDNI", typeof(string));
    
            var vFoto_ExpositorParameter = vFoto_Expositor != null ?
                new ObjectParameter("vFoto_Expositor", vFoto_Expositor) :
                new ObjectParameter("vFoto_Expositor", typeof(byte[]));
    
            var vComentarioParameter = vComentario != null ?
                new ObjectParameter("vComentario", vComentario) :
                new ObjectParameter("vComentario", typeof(string));
    
            var vId_UbigeoParameter = vId_Ubigeo != null ?
                new ObjectParameter("vId_Ubigeo", vId_Ubigeo) :
                new ObjectParameter("vId_Ubigeo", typeof(string));
    
            var vfecha_registroParameter = vfecha_registro.HasValue ?
                new ObjectParameter("vfecha_registro", vfecha_registro) :
                new ObjectParameter("vfecha_registro", typeof(System.DateTime));
    
            var vusuario_ult_modificacionParameter = vusuario_ult_modificacion != null ?
                new ObjectParameter("vusuario_ult_modificacion", vusuario_ult_modificacion) :
                new ObjectParameter("vusuario_ult_modificacion", typeof(string));
    
            var vfecha_ult_modificacionParameter = vfecha_ult_modificacion.HasValue ?
                new ObjectParameter("vfecha_ult_modificacion", vfecha_ult_modificacion) :
                new ObjectParameter("vfecha_ult_modificacion", typeof(System.DateTime));
    
            var vestado_expParameter = vestado_exp.HasValue ?
                new ObjectParameter("vestado_exp", vestado_exp) :
                new ObjectParameter("vestado_exp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarExpositor", vId_ExpositorParameter, vApellido_maternoParameter, vApellido_paternoParameter, vNombreParameter, vDirecciónParameter, vTelefonoParameter, vE_mailParameter, vDNIParameter, vFoto_ExpositorParameter, vComentarioParameter, vId_UbigeoParameter, vfecha_registroParameter, vusuario_ult_modificacionParameter, vfecha_ult_modificacionParameter, vestado_expParameter);
        }
    
        public virtual int usp_ActualizarExpositorEmpresa(string vId_Expositor, Nullable<int> vId_Empresa, Nullable<System.DateTime> vFecha_inicio, Nullable<System.DateTime> vFecha_finalizacion, string vCargo)
        {
            var vId_ExpositorParameter = vId_Expositor != null ?
                new ObjectParameter("vId_Expositor", vId_Expositor) :
                new ObjectParameter("vId_Expositor", typeof(string));
    
            var vId_EmpresaParameter = vId_Empresa.HasValue ?
                new ObjectParameter("vId_Empresa", vId_Empresa) :
                new ObjectParameter("vId_Empresa", typeof(int));
    
            var vFecha_inicioParameter = vFecha_inicio.HasValue ?
                new ObjectParameter("vFecha_inicio", vFecha_inicio) :
                new ObjectParameter("vFecha_inicio", typeof(System.DateTime));
    
            var vFecha_finalizacionParameter = vFecha_finalizacion.HasValue ?
                new ObjectParameter("vFecha_finalizacion", vFecha_finalizacion) :
                new ObjectParameter("vFecha_finalizacion", typeof(System.DateTime));
    
            var vCargoParameter = vCargo != null ?
                new ObjectParameter("vCargo", vCargo) :
                new ObjectParameter("vCargo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarExpositorEmpresa", vId_ExpositorParameter, vId_EmpresaParameter, vFecha_inicioParameter, vFecha_finalizacionParameter, vCargoParameter);
        }
    
        public virtual int usp_ActualizarUbigeo(string vId_Ubigeo, string vIdDepa, string vIdProv, string vIdDist, string vDepartamento, string vProvincia, string vDistrito)
        {
            var vId_UbigeoParameter = vId_Ubigeo != null ?
                new ObjectParameter("vId_Ubigeo", vId_Ubigeo) :
                new ObjectParameter("vId_Ubigeo", typeof(string));
    
            var vIdDepaParameter = vIdDepa != null ?
                new ObjectParameter("vIdDepa", vIdDepa) :
                new ObjectParameter("vIdDepa", typeof(string));
    
            var vIdProvParameter = vIdProv != null ?
                new ObjectParameter("vIdProv", vIdProv) :
                new ObjectParameter("vIdProv", typeof(string));
    
            var vIdDistParameter = vIdDist != null ?
                new ObjectParameter("vIdDist", vIdDist) :
                new ObjectParameter("vIdDist", typeof(string));
    
            var vDepartamentoParameter = vDepartamento != null ?
                new ObjectParameter("vDepartamento", vDepartamento) :
                new ObjectParameter("vDepartamento", typeof(string));
    
            var vProvinciaParameter = vProvincia != null ?
                new ObjectParameter("vProvincia", vProvincia) :
                new ObjectParameter("vProvincia", typeof(string));
    
            var vDistritoParameter = vDistrito != null ?
                new ObjectParameter("vDistrito", vDistrito) :
                new ObjectParameter("vDistrito", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarUbigeo", vId_UbigeoParameter, vIdDepaParameter, vIdProvParameter, vIdDistParameter, vDepartamentoParameter, vProvinciaParameter, vDistritoParameter);
        }
    
        public virtual int usp_ConsultarAsistenciaSocio(string vcod_asociado)
        {
            var vcod_asociadoParameter = vcod_asociado != null ?
                new ObjectParameter("vcod_asociado", vcod_asociado) :
                new ObjectParameter("vcod_asociado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ConsultarAsistenciaSocio", vcod_asociadoParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarAsociado_Result> usp_ConsultarAsociado(string vcod_asociado)
        {
            var vcod_asociadoParameter = vcod_asociado != null ?
                new ObjectParameter("vcod_asociado", vcod_asociado) :
                new ObjectParameter("vcod_asociado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarAsociado_Result>("usp_ConsultarAsociado", vcod_asociadoParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarCurso_Result> usp_ConsultarCurso(string vcod_curso)
        {
            var vcod_cursoParameter = vcod_curso != null ?
                new ObjectParameter("vcod_curso", vcod_curso) :
                new ObjectParameter("vcod_curso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarCurso_Result>("usp_ConsultarCurso", vcod_cursoParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarEmpresa_Result> usp_ConsultarEmpresa(Nullable<int> vId_Empresa)
        {
            var vId_EmpresaParameter = vId_Empresa.HasValue ?
                new ObjectParameter("vId_Empresa", vId_Empresa) :
                new ObjectParameter("vId_Empresa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarEmpresa_Result>("usp_ConsultarEmpresa", vId_EmpresaParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarEspecialidad_Result> usp_ConsultarEspecialidad(Nullable<int> vIdEspecialidad)
        {
            var vIdEspecialidadParameter = vIdEspecialidad.HasValue ?
                new ObjectParameter("vIdEspecialidad", vIdEspecialidad) :
                new ObjectParameter("vIdEspecialidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarEspecialidad_Result>("usp_ConsultarEspecialidad", vIdEspecialidadParameter);
        }
    
        public virtual int usp_ConsultarEspecialidadExpositor(Nullable<int> vCod_EspecialidadCurso)
        {
            var vCod_EspecialidadCursoParameter = vCod_EspecialidadCurso.HasValue ?
                new ObjectParameter("vCod_EspecialidadCurso", vCod_EspecialidadCurso) :
                new ObjectParameter("vCod_EspecialidadCurso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ConsultarEspecialidadExpositor", vCod_EspecialidadCursoParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarEvento_Result> usp_ConsultarEvento(Nullable<int> vid_evento)
        {
            var vid_eventoParameter = vid_evento.HasValue ?
                new ObjectParameter("vid_evento", vid_evento) :
                new ObjectParameter("vid_evento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarEvento_Result>("usp_ConsultarEvento", vid_eventoParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarExpositor_Result> usp_ConsultarExpositor(string vId_Expositor)
        {
            var vId_ExpositorParameter = vId_Expositor != null ?
                new ObjectParameter("vId_Expositor", vId_Expositor) :
                new ObjectParameter("vId_Expositor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarExpositor_Result>("usp_ConsultarExpositor", vId_ExpositorParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarExpositorEmpresa_Result> usp_ConsultarExpositorEmpresa(string vId_Expositor)
        {
            var vId_ExpositorParameter = vId_Expositor != null ?
                new ObjectParameter("vId_Expositor", vId_Expositor) :
                new ObjectParameter("vId_Expositor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarExpositorEmpresa_Result>("usp_ConsultarExpositorEmpresa", vId_ExpositorParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarUbigeo_Result> usp_ConsultarUbigeo(string vId_Ubigeo)
        {
            var vId_UbigeoParameter = vId_Ubigeo != null ?
                new ObjectParameter("vId_Ubigeo", vId_Ubigeo) :
                new ObjectParameter("vId_Ubigeo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarUbigeo_Result>("usp_ConsultarUbigeo", vId_UbigeoParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarUsuario_Result> usp_ConsultarUsuario(string login_Usuario)
        {
            var login_UsuarioParameter = login_Usuario != null ?
                new ObjectParameter("Login_Usuario", login_Usuario) :
                new ObjectParameter("Login_Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarUsuario_Result>("usp_ConsultarUsuario", login_UsuarioParameter);
        }
    
        public virtual int usp_EliminarAsistenciaSocio(string vcod_asociado)
        {
            var vcod_asociadoParameter = vcod_asociado != null ?
                new ObjectParameter("vcod_asociado", vcod_asociado) :
                new ObjectParameter("vcod_asociado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarAsistenciaSocio", vcod_asociadoParameter);
        }
    
        public virtual int usp_EliminarAsociado(string vcod_asociado)
        {
            var vcod_asociadoParameter = vcod_asociado != null ?
                new ObjectParameter("vcod_asociado", vcod_asociado) :
                new ObjectParameter("vcod_asociado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarAsociado", vcod_asociadoParameter);
        }
    
        public virtual int usp_EliminarCurso(string vcod_curso)
        {
            var vcod_cursoParameter = vcod_curso != null ?
                new ObjectParameter("vcod_curso", vcod_curso) :
                new ObjectParameter("vcod_curso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarCurso", vcod_cursoParameter);
        }
    
        public virtual int usp_EliminarEmpresa(Nullable<int> vId_Empresa)
        {
            var vId_EmpresaParameter = vId_Empresa.HasValue ?
                new ObjectParameter("vId_Empresa", vId_Empresa) :
                new ObjectParameter("vId_Empresa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarEmpresa", vId_EmpresaParameter);
        }
    
        public virtual int usp_EliminarEspecialidad(Nullable<int> vIdEspecialidad)
        {
            var vIdEspecialidadParameter = vIdEspecialidad.HasValue ?
                new ObjectParameter("vIdEspecialidad", vIdEspecialidad) :
                new ObjectParameter("vIdEspecialidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarEspecialidad", vIdEspecialidadParameter);
        }
    
        public virtual int usp_EliminarEspecialidadExpositor(Nullable<int> vCod_EspecialidadCurso)
        {
            var vCod_EspecialidadCursoParameter = vCod_EspecialidadCurso.HasValue ?
                new ObjectParameter("vCod_EspecialidadCurso", vCod_EspecialidadCurso) :
                new ObjectParameter("vCod_EspecialidadCurso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarEspecialidadExpositor", vCod_EspecialidadCursoParameter);
        }
    
        public virtual int usp_EliminarEvento(Nullable<int> vid_evento)
        {
            var vid_eventoParameter = vid_evento.HasValue ?
                new ObjectParameter("vid_evento", vid_evento) :
                new ObjectParameter("vid_evento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarEvento", vid_eventoParameter);
        }
    
        public virtual int usp_EliminarExpositor(string vId_Expositor)
        {
            var vId_ExpositorParameter = vId_Expositor != null ?
                new ObjectParameter("vId_Expositor", vId_Expositor) :
                new ObjectParameter("vId_Expositor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarExpositor", vId_ExpositorParameter);
        }
    
        public virtual int usp_EliminarExpositorEmpresa(string vId_Expositor)
        {
            var vId_ExpositorParameter = vId_Expositor != null ?
                new ObjectParameter("vId_Expositor", vId_Expositor) :
                new ObjectParameter("vId_Expositor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarExpositorEmpresa", vId_ExpositorParameter);
        }
    
        public virtual int usp_EliminarUbigeo(string vId_Ubigeo)
        {
            var vId_UbigeoParameter = vId_Ubigeo != null ?
                new ObjectParameter("vId_Ubigeo", vId_Ubigeo) :
                new ObjectParameter("vId_Ubigeo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarUbigeo", vId_UbigeoParameter);
        }
    
        public virtual int usp_InsertarAsistenciaSocio(string vcod_asociado, Nullable<int> vid_evento)
        {
            var vcod_asociadoParameter = vcod_asociado != null ?
                new ObjectParameter("vcod_asociado", vcod_asociado) :
                new ObjectParameter("vcod_asociado", typeof(string));
    
            var vid_eventoParameter = vid_evento.HasValue ?
                new ObjectParameter("vid_evento", vid_evento) :
                new ObjectParameter("vid_evento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarAsistenciaSocio", vcod_asociadoParameter, vid_eventoParameter);
        }
    
        public virtual int usp_InsertarAsociado(string vape_paterno, string vape_materno, string vnombres, string vdireccion, string vdni, byte[] vfoto, string vtlf_domicilio, string vtlf_celular, string vcorreo, Nullable<int> vId_Empresa, string vId_Ubigeo, string vusuario_registro, Nullable<int> vestado_aso)
        {
            var vape_paternoParameter = vape_paterno != null ?
                new ObjectParameter("vape_paterno", vape_paterno) :
                new ObjectParameter("vape_paterno", typeof(string));
    
            var vape_maternoParameter = vape_materno != null ?
                new ObjectParameter("vape_materno", vape_materno) :
                new ObjectParameter("vape_materno", typeof(string));
    
            var vnombresParameter = vnombres != null ?
                new ObjectParameter("vnombres", vnombres) :
                new ObjectParameter("vnombres", typeof(string));
    
            var vdireccionParameter = vdireccion != null ?
                new ObjectParameter("vdireccion", vdireccion) :
                new ObjectParameter("vdireccion", typeof(string));
    
            var vdniParameter = vdni != null ?
                new ObjectParameter("vdni", vdni) :
                new ObjectParameter("vdni", typeof(string));
    
            var vfotoParameter = vfoto != null ?
                new ObjectParameter("vfoto", vfoto) :
                new ObjectParameter("vfoto", typeof(byte[]));
    
            var vtlf_domicilioParameter = vtlf_domicilio != null ?
                new ObjectParameter("vtlf_domicilio", vtlf_domicilio) :
                new ObjectParameter("vtlf_domicilio", typeof(string));
    
            var vtlf_celularParameter = vtlf_celular != null ?
                new ObjectParameter("vtlf_celular", vtlf_celular) :
                new ObjectParameter("vtlf_celular", typeof(string));
    
            var vcorreoParameter = vcorreo != null ?
                new ObjectParameter("vcorreo", vcorreo) :
                new ObjectParameter("vcorreo", typeof(string));
    
            var vId_EmpresaParameter = vId_Empresa.HasValue ?
                new ObjectParameter("vId_Empresa", vId_Empresa) :
                new ObjectParameter("vId_Empresa", typeof(int));
    
            var vId_UbigeoParameter = vId_Ubigeo != null ?
                new ObjectParameter("vId_Ubigeo", vId_Ubigeo) :
                new ObjectParameter("vId_Ubigeo", typeof(string));
    
            var vusuario_registroParameter = vusuario_registro != null ?
                new ObjectParameter("vusuario_registro", vusuario_registro) :
                new ObjectParameter("vusuario_registro", typeof(string));
    
            var vestado_asoParameter = vestado_aso.HasValue ?
                new ObjectParameter("vestado_aso", vestado_aso) :
                new ObjectParameter("vestado_aso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarAsociado", vape_paternoParameter, vape_maternoParameter, vnombresParameter, vdireccionParameter, vdniParameter, vfotoParameter, vtlf_domicilioParameter, vtlf_celularParameter, vcorreoParameter, vId_EmpresaParameter, vId_UbigeoParameter, vusuario_registroParameter, vestado_asoParameter);
        }
    
        public virtual int usp_InsertarCurso(string vdescripcion, Nullable<int> vhoras_teoria, Nullable<int> vhoras_practica, string vnivel_dificultad, string vcomentarios, Nullable<int> vIdEspecialidad, string vusuario_registro, Nullable<int> vestado_cur)
        {
            var vdescripcionParameter = vdescripcion != null ?
                new ObjectParameter("vdescripcion", vdescripcion) :
                new ObjectParameter("vdescripcion", typeof(string));
    
            var vhoras_teoriaParameter = vhoras_teoria.HasValue ?
                new ObjectParameter("vhoras_teoria", vhoras_teoria) :
                new ObjectParameter("vhoras_teoria", typeof(int));
    
            var vhoras_practicaParameter = vhoras_practica.HasValue ?
                new ObjectParameter("vhoras_practica", vhoras_practica) :
                new ObjectParameter("vhoras_practica", typeof(int));
    
            var vnivel_dificultadParameter = vnivel_dificultad != null ?
                new ObjectParameter("vnivel_dificultad", vnivel_dificultad) :
                new ObjectParameter("vnivel_dificultad", typeof(string));
    
            var vcomentariosParameter = vcomentarios != null ?
                new ObjectParameter("vcomentarios", vcomentarios) :
                new ObjectParameter("vcomentarios", typeof(string));
    
            var vIdEspecialidadParameter = vIdEspecialidad.HasValue ?
                new ObjectParameter("vIdEspecialidad", vIdEspecialidad) :
                new ObjectParameter("vIdEspecialidad", typeof(int));
    
            var vusuario_registroParameter = vusuario_registro != null ?
                new ObjectParameter("vusuario_registro", vusuario_registro) :
                new ObjectParameter("vusuario_registro", typeof(string));
    
            var vestado_curParameter = vestado_cur.HasValue ?
                new ObjectParameter("vestado_cur", vestado_cur) :
                new ObjectParameter("vestado_cur", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarCurso", vdescripcionParameter, vhoras_teoriaParameter, vhoras_practicaParameter, vnivel_dificultadParameter, vcomentariosParameter, vIdEspecialidadParameter, vusuario_registroParameter, vestado_curParameter);
        }
    
        public virtual int usp_InsertarEmpresa(Nullable<int> vId_Empresa, string vRazon_Social, string vDireccion, string vTelefono1, string vTelefono2, string vUrlPagWeb, string vId_Ubigeo, Nullable<System.DateTime> vfecha_registro, string vusuario_ult_modificacion, Nullable<System.DateTime> vfecha_ult_modificacion, Nullable<int> vestado_emp)
        {
            var vId_EmpresaParameter = vId_Empresa.HasValue ?
                new ObjectParameter("vId_Empresa", vId_Empresa) :
                new ObjectParameter("vId_Empresa", typeof(int));
    
            var vRazon_SocialParameter = vRazon_Social != null ?
                new ObjectParameter("vRazon_Social", vRazon_Social) :
                new ObjectParameter("vRazon_Social", typeof(string));
    
            var vDireccionParameter = vDireccion != null ?
                new ObjectParameter("vDireccion", vDireccion) :
                new ObjectParameter("vDireccion", typeof(string));
    
            var vTelefono1Parameter = vTelefono1 != null ?
                new ObjectParameter("vTelefono1", vTelefono1) :
                new ObjectParameter("vTelefono1", typeof(string));
    
            var vTelefono2Parameter = vTelefono2 != null ?
                new ObjectParameter("vTelefono2", vTelefono2) :
                new ObjectParameter("vTelefono2", typeof(string));
    
            var vUrlPagWebParameter = vUrlPagWeb != null ?
                new ObjectParameter("vUrlPagWeb", vUrlPagWeb) :
                new ObjectParameter("vUrlPagWeb", typeof(string));
    
            var vId_UbigeoParameter = vId_Ubigeo != null ?
                new ObjectParameter("vId_Ubigeo", vId_Ubigeo) :
                new ObjectParameter("vId_Ubigeo", typeof(string));
    
            var vfecha_registroParameter = vfecha_registro.HasValue ?
                new ObjectParameter("vfecha_registro", vfecha_registro) :
                new ObjectParameter("vfecha_registro", typeof(System.DateTime));
    
            var vusuario_ult_modificacionParameter = vusuario_ult_modificacion != null ?
                new ObjectParameter("vusuario_ult_modificacion", vusuario_ult_modificacion) :
                new ObjectParameter("vusuario_ult_modificacion", typeof(string));
    
            var vfecha_ult_modificacionParameter = vfecha_ult_modificacion.HasValue ?
                new ObjectParameter("vfecha_ult_modificacion", vfecha_ult_modificacion) :
                new ObjectParameter("vfecha_ult_modificacion", typeof(System.DateTime));
    
            var vestado_empParameter = vestado_emp.HasValue ?
                new ObjectParameter("vestado_emp", vestado_emp) :
                new ObjectParameter("vestado_emp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarEmpresa", vId_EmpresaParameter, vRazon_SocialParameter, vDireccionParameter, vTelefono1Parameter, vTelefono2Parameter, vUrlPagWebParameter, vId_UbigeoParameter, vfecha_registroParameter, vusuario_ult_modificacionParameter, vfecha_ult_modificacionParameter, vestado_empParameter);
        }
    
        public virtual int usp_InsertarEspecialidad(Nullable<int> vIdEspecialidad, string vDescEspecialidad)
        {
            var vIdEspecialidadParameter = vIdEspecialidad.HasValue ?
                new ObjectParameter("vIdEspecialidad", vIdEspecialidad) :
                new ObjectParameter("vIdEspecialidad", typeof(int));
    
            var vDescEspecialidadParameter = vDescEspecialidad != null ?
                new ObjectParameter("vDescEspecialidad", vDescEspecialidad) :
                new ObjectParameter("vDescEspecialidad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarEspecialidad", vIdEspecialidadParameter, vDescEspecialidadParameter);
        }
    
        public virtual int usp_InsertarEspecialidadExpositor(Nullable<int> vCod_EspecialidadCurso, Nullable<int> vIdEspecialidad, string vId_Expositor)
        {
            var vCod_EspecialidadCursoParameter = vCod_EspecialidadCurso.HasValue ?
                new ObjectParameter("vCod_EspecialidadCurso", vCod_EspecialidadCurso) :
                new ObjectParameter("vCod_EspecialidadCurso", typeof(int));
    
            var vIdEspecialidadParameter = vIdEspecialidad.HasValue ?
                new ObjectParameter("vIdEspecialidad", vIdEspecialidad) :
                new ObjectParameter("vIdEspecialidad", typeof(int));
    
            var vId_ExpositorParameter = vId_Expositor != null ?
                new ObjectParameter("vId_Expositor", vId_Expositor) :
                new ObjectParameter("vId_Expositor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarEspecialidadExpositor", vCod_EspecialidadCursoParameter, vIdEspecialidadParameter, vId_ExpositorParameter);
        }
    
        public virtual int usp_InsertarEvento(Nullable<int> vId_Empresa, Nullable<int> vid_frecuencia, Nullable<int> vid_turno, Nullable<decimal> vpresupuesto_requerido, string vdireccion_evento, Nullable<int> vcupos_programados, Nullable<System.DateTime> vfecha_inicio, Nullable<System.DateTime> vfecha_fin, string vId_Expositor, string vId_Ubigeo, string vcod_curso, string vusuario_registro, Nullable<int> vestado_eve)
        {
            var vId_EmpresaParameter = vId_Empresa.HasValue ?
                new ObjectParameter("vId_Empresa", vId_Empresa) :
                new ObjectParameter("vId_Empresa", typeof(int));
    
            var vid_frecuenciaParameter = vid_frecuencia.HasValue ?
                new ObjectParameter("vid_frecuencia", vid_frecuencia) :
                new ObjectParameter("vid_frecuencia", typeof(int));
    
            var vid_turnoParameter = vid_turno.HasValue ?
                new ObjectParameter("vid_turno", vid_turno) :
                new ObjectParameter("vid_turno", typeof(int));
    
            var vpresupuesto_requeridoParameter = vpresupuesto_requerido.HasValue ?
                new ObjectParameter("vpresupuesto_requerido", vpresupuesto_requerido) :
                new ObjectParameter("vpresupuesto_requerido", typeof(decimal));
    
            var vdireccion_eventoParameter = vdireccion_evento != null ?
                new ObjectParameter("vdireccion_evento", vdireccion_evento) :
                new ObjectParameter("vdireccion_evento", typeof(string));
    
            var vcupos_programadosParameter = vcupos_programados.HasValue ?
                new ObjectParameter("vcupos_programados", vcupos_programados) :
                new ObjectParameter("vcupos_programados", typeof(int));
    
            var vfecha_inicioParameter = vfecha_inicio.HasValue ?
                new ObjectParameter("vfecha_inicio", vfecha_inicio) :
                new ObjectParameter("vfecha_inicio", typeof(System.DateTime));
    
            var vfecha_finParameter = vfecha_fin.HasValue ?
                new ObjectParameter("vfecha_fin", vfecha_fin) :
                new ObjectParameter("vfecha_fin", typeof(System.DateTime));
    
            var vId_ExpositorParameter = vId_Expositor != null ?
                new ObjectParameter("vId_Expositor", vId_Expositor) :
                new ObjectParameter("vId_Expositor", typeof(string));
    
            var vId_UbigeoParameter = vId_Ubigeo != null ?
                new ObjectParameter("vId_Ubigeo", vId_Ubigeo) :
                new ObjectParameter("vId_Ubigeo", typeof(string));
    
            var vcod_cursoParameter = vcod_curso != null ?
                new ObjectParameter("vcod_curso", vcod_curso) :
                new ObjectParameter("vcod_curso", typeof(string));
    
            var vusuario_registroParameter = vusuario_registro != null ?
                new ObjectParameter("vusuario_registro", vusuario_registro) :
                new ObjectParameter("vusuario_registro", typeof(string));
    
            var vestado_eveParameter = vestado_eve.HasValue ?
                new ObjectParameter("vestado_eve", vestado_eve) :
                new ObjectParameter("vestado_eve", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarEvento", vId_EmpresaParameter, vid_frecuenciaParameter, vid_turnoParameter, vpresupuesto_requeridoParameter, vdireccion_eventoParameter, vcupos_programadosParameter, vfecha_inicioParameter, vfecha_finParameter, vId_ExpositorParameter, vId_UbigeoParameter, vcod_cursoParameter, vusuario_registroParameter, vestado_eveParameter);
        }
    
        public virtual int usp_InsertarExpositor(string vId_Expositor, string vApellido_materno, string vApellido_paterno, string vNombre, string vDirección, string vTelefono, string vE_mail, string vDNI, byte[] vFoto_Expositor, string vComentario, string vId_Ubigeo, Nullable<System.DateTime> vfecha_registro, string vusuario_ult_modificacion, Nullable<System.DateTime> vfecha_ult_modificacion, Nullable<int> vestado_exp)
        {
            var vId_ExpositorParameter = vId_Expositor != null ?
                new ObjectParameter("vId_Expositor", vId_Expositor) :
                new ObjectParameter("vId_Expositor", typeof(string));
    
            var vApellido_maternoParameter = vApellido_materno != null ?
                new ObjectParameter("vApellido_materno", vApellido_materno) :
                new ObjectParameter("vApellido_materno", typeof(string));
    
            var vApellido_paternoParameter = vApellido_paterno != null ?
                new ObjectParameter("vApellido_paterno", vApellido_paterno) :
                new ObjectParameter("vApellido_paterno", typeof(string));
    
            var vNombreParameter = vNombre != null ?
                new ObjectParameter("vNombre", vNombre) :
                new ObjectParameter("vNombre", typeof(string));
    
            var vDirecciónParameter = vDirección != null ?
                new ObjectParameter("vDirección", vDirección) :
                new ObjectParameter("vDirección", typeof(string));
    
            var vTelefonoParameter = vTelefono != null ?
                new ObjectParameter("vTelefono", vTelefono) :
                new ObjectParameter("vTelefono", typeof(string));
    
            var vE_mailParameter = vE_mail != null ?
                new ObjectParameter("vE_mail", vE_mail) :
                new ObjectParameter("vE_mail", typeof(string));
    
            var vDNIParameter = vDNI != null ?
                new ObjectParameter("vDNI", vDNI) :
                new ObjectParameter("vDNI", typeof(string));
    
            var vFoto_ExpositorParameter = vFoto_Expositor != null ?
                new ObjectParameter("vFoto_Expositor", vFoto_Expositor) :
                new ObjectParameter("vFoto_Expositor", typeof(byte[]));
    
            var vComentarioParameter = vComentario != null ?
                new ObjectParameter("vComentario", vComentario) :
                new ObjectParameter("vComentario", typeof(string));
    
            var vId_UbigeoParameter = vId_Ubigeo != null ?
                new ObjectParameter("vId_Ubigeo", vId_Ubigeo) :
                new ObjectParameter("vId_Ubigeo", typeof(string));
    
            var vfecha_registroParameter = vfecha_registro.HasValue ?
                new ObjectParameter("vfecha_registro", vfecha_registro) :
                new ObjectParameter("vfecha_registro", typeof(System.DateTime));
    
            var vusuario_ult_modificacionParameter = vusuario_ult_modificacion != null ?
                new ObjectParameter("vusuario_ult_modificacion", vusuario_ult_modificacion) :
                new ObjectParameter("vusuario_ult_modificacion", typeof(string));
    
            var vfecha_ult_modificacionParameter = vfecha_ult_modificacion.HasValue ?
                new ObjectParameter("vfecha_ult_modificacion", vfecha_ult_modificacion) :
                new ObjectParameter("vfecha_ult_modificacion", typeof(System.DateTime));
    
            var vestado_expParameter = vestado_exp.HasValue ?
                new ObjectParameter("vestado_exp", vestado_exp) :
                new ObjectParameter("vestado_exp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarExpositor", vId_ExpositorParameter, vApellido_maternoParameter, vApellido_paternoParameter, vNombreParameter, vDirecciónParameter, vTelefonoParameter, vE_mailParameter, vDNIParameter, vFoto_ExpositorParameter, vComentarioParameter, vId_UbigeoParameter, vfecha_registroParameter, vusuario_ult_modificacionParameter, vfecha_ult_modificacionParameter, vestado_expParameter);
        }
    
        public virtual int usp_InsertarExpositorEmpresa(string vId_Expositor, Nullable<int> vId_Empresa, Nullable<System.DateTime> vFecha_inicio, Nullable<System.DateTime> vFecha_finalizacion, string vCargo)
        {
            var vId_ExpositorParameter = vId_Expositor != null ?
                new ObjectParameter("vId_Expositor", vId_Expositor) :
                new ObjectParameter("vId_Expositor", typeof(string));
    
            var vId_EmpresaParameter = vId_Empresa.HasValue ?
                new ObjectParameter("vId_Empresa", vId_Empresa) :
                new ObjectParameter("vId_Empresa", typeof(int));
    
            var vFecha_inicioParameter = vFecha_inicio.HasValue ?
                new ObjectParameter("vFecha_inicio", vFecha_inicio) :
                new ObjectParameter("vFecha_inicio", typeof(System.DateTime));
    
            var vFecha_finalizacionParameter = vFecha_finalizacion.HasValue ?
                new ObjectParameter("vFecha_finalizacion", vFecha_finalizacion) :
                new ObjectParameter("vFecha_finalizacion", typeof(System.DateTime));
    
            var vCargoParameter = vCargo != null ?
                new ObjectParameter("vCargo", vCargo) :
                new ObjectParameter("vCargo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarExpositorEmpresa", vId_ExpositorParameter, vId_EmpresaParameter, vFecha_inicioParameter, vFecha_finalizacionParameter, vCargoParameter);
        }
    
        public virtual int usp_InsertarUbigeo(string vId_Ubigeo, string vIdDepa, string vIdProv, string vIdDist, string vDepartamento, string vProvincia, string vDistrito)
        {
            var vId_UbigeoParameter = vId_Ubigeo != null ?
                new ObjectParameter("vId_Ubigeo", vId_Ubigeo) :
                new ObjectParameter("vId_Ubigeo", typeof(string));
    
            var vIdDepaParameter = vIdDepa != null ?
                new ObjectParameter("vIdDepa", vIdDepa) :
                new ObjectParameter("vIdDepa", typeof(string));
    
            var vIdProvParameter = vIdProv != null ?
                new ObjectParameter("vIdProv", vIdProv) :
                new ObjectParameter("vIdProv", typeof(string));
    
            var vIdDistParameter = vIdDist != null ?
                new ObjectParameter("vIdDist", vIdDist) :
                new ObjectParameter("vIdDist", typeof(string));
    
            var vDepartamentoParameter = vDepartamento != null ?
                new ObjectParameter("vDepartamento", vDepartamento) :
                new ObjectParameter("vDepartamento", typeof(string));
    
            var vProvinciaParameter = vProvincia != null ?
                new ObjectParameter("vProvincia", vProvincia) :
                new ObjectParameter("vProvincia", typeof(string));
    
            var vDistritoParameter = vDistrito != null ?
                new ObjectParameter("vDistrito", vDistrito) :
                new ObjectParameter("vDistrito", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarUbigeo", vId_UbigeoParameter, vIdDepaParameter, vIdProvParameter, vIdDistParameter, vDepartamentoParameter, vProvinciaParameter, vDistritoParameter);
        }
    
        public virtual int usp_InsertarUsuario(string login_Usuario, string pass_Usuario, Nullable<int> niv_Usuario, Nullable<int> est_Usuario, string usu_Registro)
        {
            var login_UsuarioParameter = login_Usuario != null ?
                new ObjectParameter("Login_Usuario", login_Usuario) :
                new ObjectParameter("Login_Usuario", typeof(string));
    
            var pass_UsuarioParameter = pass_Usuario != null ?
                new ObjectParameter("Pass_Usuario", pass_Usuario) :
                new ObjectParameter("Pass_Usuario", typeof(string));
    
            var niv_UsuarioParameter = niv_Usuario.HasValue ?
                new ObjectParameter("Niv_Usuario", niv_Usuario) :
                new ObjectParameter("Niv_Usuario", typeof(int));
    
            var est_UsuarioParameter = est_Usuario.HasValue ?
                new ObjectParameter("Est_Usuario", est_Usuario) :
                new ObjectParameter("Est_Usuario", typeof(int));
    
            var usu_RegistroParameter = usu_Registro != null ?
                new ObjectParameter("Usu_Registro", usu_Registro) :
                new ObjectParameter("Usu_Registro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarUsuario", login_UsuarioParameter, pass_UsuarioParameter, niv_UsuarioParameter, est_UsuarioParameter, usu_RegistroParameter);
        }
    
        public virtual int usp_ListarAsistenciasSocio(string vcod_asociado)
        {
            var vcod_asociadoParameter = vcod_asociado != null ?
                new ObjectParameter("vcod_asociado", vcod_asociado) :
                new ObjectParameter("vcod_asociado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ListarAsistenciasSocio", vcod_asociadoParameter);
        }
    
        public virtual ObjectResult<usp_ListarAsociados_Result> usp_ListarAsociados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarAsociados_Result>("usp_ListarAsociados");
        }
    
        public virtual ObjectResult<usp_ListarCursos_Result> usp_ListarCursos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarCursos_Result>("usp_ListarCursos");
        }
    
        public virtual ObjectResult<usp_ListarEmpresas_Result> usp_ListarEmpresas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarEmpresas_Result>("usp_ListarEmpresas");
        }
    
        public virtual ObjectResult<usp_ListarEspecialidades_Result> usp_ListarEspecialidades()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarEspecialidades_Result>("usp_ListarEspecialidades");
        }
    
        public virtual ObjectResult<usp_ListarEspecialidadesExpositores_Result> usp_ListarEspecialidadesExpositores(Nullable<int> vIdEspecialidad)
        {
            var vIdEspecialidadParameter = vIdEspecialidad.HasValue ?
                new ObjectParameter("vIdEspecialidad", vIdEspecialidad) :
                new ObjectParameter("vIdEspecialidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarEspecialidadesExpositores_Result>("usp_ListarEspecialidadesExpositores", vIdEspecialidadParameter);
        }
    
        public virtual ObjectResult<usp_ListarEventos_Result> usp_ListarEventos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarEventos_Result>("usp_ListarEventos");
        }
    
        public virtual ObjectResult<usp_ListarExpositores_Result> usp_ListarExpositores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarExpositores_Result>("usp_ListarExpositores");
        }
    
        public virtual ObjectResult<usp_ListarExpositoresEmpresas_Result> usp_ListarExpositoresEmpresas(string vId_Expositor)
        {
            var vId_ExpositorParameter = vId_Expositor != null ?
                new ObjectParameter("vId_Expositor", vId_Expositor) :
                new ObjectParameter("vId_Expositor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarExpositoresEmpresas_Result>("usp_ListarExpositoresEmpresas", vId_ExpositorParameter);
        }
    
        public virtual ObjectResult<usp_ListarUbigeos_Result> usp_ListarUbigeos(string vId_Ubigeo)
        {
            var vId_UbigeoParameter = vId_Ubigeo != null ?
                new ObjectParameter("vId_Ubigeo", vId_Ubigeo) :
                new ObjectParameter("vId_Ubigeo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarUbigeos_Result>("usp_ListarUbigeos", vId_UbigeoParameter);
        }
    
        public virtual ObjectResult<usp_ObtenerAsociadoPorFechaIngreso_Result> usp_ObtenerAsociadoPorFechaIngreso(Nullable<System.DateTime> fecIngreso)
        {
            var fecIngresoParameter = fecIngreso.HasValue ?
                new ObjectParameter("fecIngreso", fecIngreso) :
                new ObjectParameter("fecIngreso", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenerAsociadoPorFechaIngreso_Result>("usp_ObtenerAsociadoPorFechaIngreso", fecIngresoParameter);
        }
    
        public virtual ObjectResult<usp_ObtenerAsociadosPorEvento_Result> usp_ObtenerAsociadosPorEvento(Nullable<int> id_evento)
        {
            var id_eventoParameter = id_evento.HasValue ?
                new ObjectParameter("id_evento", id_evento) :
                new ObjectParameter("id_evento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenerAsociadosPorEvento_Result>("usp_ObtenerAsociadosPorEvento", id_eventoParameter);
        }
    
        public virtual ObjectResult<usp_ObtenerCursosPorDificultad_Result> usp_ObtenerCursosPorDificultad(string nivel_dificultad)
        {
            var nivel_dificultadParameter = nivel_dificultad != null ?
                new ObjectParameter("nivel_dificultad", nivel_dificultad) :
                new ObjectParameter("nivel_dificultad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenerCursosPorDificultad_Result>("usp_ObtenerCursosPorDificultad", nivel_dificultadParameter);
        }
    
        public virtual ObjectResult<usp_ObtenerEventosPorExpositor_Result> usp_ObtenerEventosPorExpositor(string id_Expositor)
        {
            var id_ExpositorParameter = id_Expositor != null ?
                new ObjectParameter("Id_Expositor", id_Expositor) :
                new ObjectParameter("Id_Expositor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenerEventosPorExpositor_Result>("usp_ObtenerEventosPorExpositor", id_ExpositorParameter);
        }
    
        public virtual ObjectResult<usp_PresupuestoCuposPorMes_Result> usp_PresupuestoCuposPorMes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PresupuestoCuposPorMes_Result>("usp_PresupuestoCuposPorMes");
        }
    
        public virtual ObjectResult<usp_Ubigeo_Departamentos_Result> usp_Ubigeo_Departamentos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Ubigeo_Departamentos_Result>("usp_Ubigeo_Departamentos");
        }
    
        public virtual ObjectResult<usp_Ubigeo_DistritosProvinciaDepartamento_Result> usp_Ubigeo_DistritosProvinciaDepartamento(string idDepartamento, string idProvincia)
        {
            var idDepartamentoParameter = idDepartamento != null ?
                new ObjectParameter("IdDepartamento", idDepartamento) :
                new ObjectParameter("IdDepartamento", typeof(string));
    
            var idProvinciaParameter = idProvincia != null ?
                new ObjectParameter("IdProvincia", idProvincia) :
                new ObjectParameter("IdProvincia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Ubigeo_DistritosProvinciaDepartamento_Result>("usp_Ubigeo_DistritosProvinciaDepartamento", idDepartamentoParameter, idProvinciaParameter);
        }
    
        public virtual ObjectResult<usp_Ubigeo_ProvinciasDepartamento_Result> usp_Ubigeo_ProvinciasDepartamento(string idDepartamento)
        {
            var idDepartamentoParameter = idDepartamento != null ?
                new ObjectParameter("IdDepartamento", idDepartamento) :
                new ObjectParameter("IdDepartamento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Ubigeo_ProvinciasDepartamento_Result>("usp_Ubigeo_ProvinciasDepartamento", idDepartamentoParameter);
        }
    
        public virtual ObjectResult<usp_ventosPorLugar_Result> usp_ventosPorLugar(string lugar, string turno, string expositor, Nullable<int> empresa, string asociado, string ape_aso, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> estado)
        {
            var lugarParameter = lugar != null ?
                new ObjectParameter("lugar", lugar) :
                new ObjectParameter("lugar", typeof(string));
    
            var turnoParameter = turno != null ?
                new ObjectParameter("turno", turno) :
                new ObjectParameter("turno", typeof(string));
    
            var expositorParameter = expositor != null ?
                new ObjectParameter("expositor", expositor) :
                new ObjectParameter("expositor", typeof(string));
    
            var empresaParameter = empresa.HasValue ?
                new ObjectParameter("empresa", empresa) :
                new ObjectParameter("empresa", typeof(int));
    
            var asociadoParameter = asociado != null ?
                new ObjectParameter("asociado", asociado) :
                new ObjectParameter("asociado", typeof(string));
    
            var ape_asoParameter = ape_aso != null ?
                new ObjectParameter("ape_aso", ape_aso) :
                new ObjectParameter("ape_aso", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ventosPorLugar_Result>("usp_ventosPorLugar", lugarParameter, turnoParameter, expositorParameter, empresaParameter, asociadoParameter, ape_asoParameter, fechaInicioParameter, fechaFinParameter, estadoParameter);
        }
    
        public virtual ObjectResult<usp_eventosPorLugar_Result> usp_eventosPorLugar(string lugar, string turno, string expositor, Nullable<int> empresa, string asociado, string ape_aso, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> estado)
        {
            var lugarParameter = lugar != null ?
                new ObjectParameter("lugar", lugar) :
                new ObjectParameter("lugar", typeof(string));
    
            var turnoParameter = turno != null ?
                new ObjectParameter("turno", turno) :
                new ObjectParameter("turno", typeof(string));
    
            var expositorParameter = expositor != null ?
                new ObjectParameter("expositor", expositor) :
                new ObjectParameter("expositor", typeof(string));
    
            var empresaParameter = empresa.HasValue ?
                new ObjectParameter("empresa", empresa) :
                new ObjectParameter("empresa", typeof(int));
    
            var asociadoParameter = asociado != null ?
                new ObjectParameter("asociado", asociado) :
                new ObjectParameter("asociado", typeof(string));
    
            var ape_asoParameter = ape_aso != null ?
                new ObjectParameter("ape_aso", ape_aso) :
                new ObjectParameter("ape_aso", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_eventosPorLugar_Result>("usp_eventosPorLugar", lugarParameter, turnoParameter, expositorParameter, empresaParameter, asociadoParameter, ape_asoParameter, fechaInicioParameter, fechaFinParameter, estadoParameter);
        }
    
        public virtual ObjectResult<usp_consultarAsociadosInscritos_Result> usp_consultarAsociadosInscritos(string lugar, string turno, string expositor, Nullable<int> empresa, string asociado, string ape_aso, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> estado)
        {
            var lugarParameter = lugar != null ?
                new ObjectParameter("lugar", lugar) :
                new ObjectParameter("lugar", typeof(string));
    
            var turnoParameter = turno != null ?
                new ObjectParameter("turno", turno) :
                new ObjectParameter("turno", typeof(string));
    
            var expositorParameter = expositor != null ?
                new ObjectParameter("expositor", expositor) :
                new ObjectParameter("expositor", typeof(string));
    
            var empresaParameter = empresa.HasValue ?
                new ObjectParameter("empresa", empresa) :
                new ObjectParameter("empresa", typeof(int));
    
            var asociadoParameter = asociado != null ?
                new ObjectParameter("asociado", asociado) :
                new ObjectParameter("asociado", typeof(string));
    
            var ape_asoParameter = ape_aso != null ?
                new ObjectParameter("ape_aso", ape_aso) :
                new ObjectParameter("ape_aso", typeof(string));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_consultarAsociadosInscritos_Result>("usp_consultarAsociadosInscritos", lugarParameter, turnoParameter, expositorParameter, empresaParameter, asociadoParameter, ape_asoParameter, fechaInicioParameter, fechaFinParameter, estadoParameter);
        }
    }
}
